### ISSUE TITLE
Example task

### ISSUE THREAD

**Issue by Azuremis** [chingu-voyages/v42-bears-team-26#35]
**__Task Description__**
Describe the task to be completed.

**__Technical Considerations__**
Include any technical considerations including architecture (e.g. API), required libraries, etc.

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**__Success Criteria__**
What does success look like

**Comment by fmtabbara** [comment]
:100:

**Comment by Azuremis** [comment]
Closing to tidy up project backlog (this was an experimental issue to help us workout how to use zenhub)
