### ISSUE TITLE
CAN'T ACCESS DISCORD

### ISSUE THREAD

**Issue by sandramsc** [chingu-voyages/v42-bears-team-26#88]

**Comment by sandramsc** [comment]
Hey guys, can you guys log into discord? I haven't been able to for the past hour. Messaging on here because I don't seem to have any of ya'lls emails.

**Comment by 0marwa0** [comment]
Hi Sandra,  yes, I'm able to log into discord, did you try to update it?

**Comment by sandramsc** [comment]
@0marwa0 I use the desktop version, contacted their support team, hopefully they can help resolve soon.

**Comment by sandramsc** [comment]
able to login, strange that it showed no errors regarding.
